import * as fs   from 'fs';
import * as path from 'path';
import { GraphDB }    from '../graph/graphDB';
import { GraphStats } from '../types';

export class SkillGenerator {
  constructor(private db: GraphDB) {}

  generateAll(workspaceRoot: string, _stats: GraphStats): string[] {
    const written: string[] = [];
    const codelensDir = path.join(workspaceRoot, '.codelens');
    fs.mkdirSync(codelensDir, { recursive: true });

    // .codelens/README.md
    fs.writeFileSync(path.join(codelensDir, 'README.md'), this.buildReadme(workspaceRoot), 'utf-8');
    written.push('.codelens/README.md');

    // .codelens/mcp.json — reference config for all agents
    fs.writeFileSync(path.join(codelensDir, 'mcp.json'), this.buildMcpConfig(workspaceRoot), 'utf-8');
    written.push('.codelens/mcp.json');

    // .vscode/mcp.json — VS Code reads this automatically, no user action needed
    if (this.writeVsCodeMcpConfig(workspaceRoot)) {
      written.push('.vscode/mcp.json');
    }

    this.ensureGitignore(workspaceRoot);
    return written;
  }

  removeAll(workspaceRoot: string): void {
    const legacy = [
      '.cursor/rules/codelens.mdc', '.cursorrules',
      '.github/copilot-instructions.md', '.clinerules',
      '.vscode/codelens.instructions.md', 'CONVENTIONS.md',
    ];
    for (const rel of legacy) {
      const fp = path.join(workspaceRoot, rel);
      if (!fs.existsSync(fp)) { continue; }
      try {
        const c = fs.readFileSync(fp, 'utf-8');
        if (c.includes('CODELENS_MANAGED_START')) {
          const cleaned = this.removeManagedSection(c);
          if (cleaned.trim()) { fs.writeFileSync(fp, cleaned, 'utf-8'); }
          else { fs.unlinkSync(fp); }
        }
      } catch { /* ignore */ }
    }
  }

  // ── Path helpers ─────────────────────────────────────────────────────────────

  private getMcpEntryPath(): string {
    // __dirname at runtime = dist/ (esbuild output directory)
    // mcp.js is the bundled MCP server in the same dist/ folder
    const p = path.resolve(__dirname, 'mcp.js');
    // Always use forward slashes — works on Windows too for node args
    return p.replace(/\\/g, '/');
  }

  private toFwdSlash(p: string): string {
    return p.replace(/\\/g, '/');
  }

  // ── VS Code mcp.json ──────────────────────────────────────────────────────────
  // Written automatically on every scan so the MCP server is always up to date.
  // VS Code picks this up without any user action.

  private writeVsCodeMcpConfig(workspaceRoot: string): boolean {
    const vscodeDir  = path.join(workspaceRoot, '.vscode');
    const configPath = path.join(vscodeDir, 'mcp.json');

    let existing: Record<string, unknown> = {};
    if (fs.existsSync(configPath)) {
      try { existing = JSON.parse(fs.readFileSync(configPath, 'utf-8')); }
      catch { /* corrupt file — overwrite */ }
    }

    const updated = {
      ...existing,
      servers: {
        ...(existing['servers'] as Record<string, unknown> ?? {}),
        codelens: {
          // VS Code MCP format: command + args
          command: 'node',
          args: [this.getMcpEntryPath(), this.toFwdSlash(workspaceRoot)],
        },
      },
    };

    try {
      fs.mkdirSync(vscodeDir, { recursive: true });
      fs.writeFileSync(configPath, JSON.stringify(updated, null, 2) + '\n', 'utf-8');
      return true;
    } catch {
      return false;
    }
  }

  // ── Reference config for other agents ────────────────────────────────────────

  private buildMcpConfig(workspaceRoot: string): string {
    const entryPath   = this.getMcpEntryPath();
    const projectPath = this.toFwdSlash(workspaceRoot);

    return JSON.stringify({
      _comment: 'CodeLens Graph MCP — copy the relevant section to your agent config',
      vscode: {
        _note: 'Auto-written to .vscode/mcp.json — no action needed',
        servers: { codelens: { command: 'node', args: [entryPath, projectPath] } },
      },
      claude_code: {
        _add_to: '~/.claude.json under mcpServers',
        codelens: { type: 'stdio', command: 'node', args: [entryPath, projectPath] },
      },
      cursor: {
        _add_to: '~/.cursor/mcp.json or .cursor/mcp.json in project',
        codelens: { command: 'node', args: [entryPath, projectPath] },
      },
      cline: {
        _add_to: 'Cline MCP Settings → Add Server → Stdio',
        command: 'node',
        args: [entryPath, projectPath],
      },
    }, null, 2);
  }

  // ── README ────────────────────────────────────────────────────────────────────

  private buildReadme(workspaceRoot: string): string {
    const entryPath   = this.getMcpEntryPath();
    const projectPath = this.toFwdSlash(workspaceRoot);

    return `# CodeLens Graph

Local codebase index — auto-generated by the CodeLens Graph VS Code extension.

## Files
- \`codelens-graph.db\` — SQLite graph (symbols + relationships)
- \`mcp.json\`         — MCP server config for all agents
- \`README.md\`        — This file

## Status
The graph is updated automatically every time you save a source file.
\`.vscode/mcp.json\` is kept in sync — VS Code picks it up automatically.

## MCP Tools available
| Tool | Use when |
|------|---------|
| \`codelens_triage\`  | First call on every task — picks minimum tool needed |
| \`codelens_search\`  | Symbol/file location unknown |
| \`codelens_context\` | Feature or bug fix needing cross-file awareness |
| \`codelens_callers\` | Before changing a shared API |
| \`codelens_callees\` | Understanding a function's dependencies |
| \`codelens_impact\`  | Before a refactor — full blast radius |
| \`codelens_node\`    | Inspect one symbol without reading the file |
| \`codelens_files\`   | Project structure discovery |
| \`codelens_status\`  | Verify the index is current |

## Manual connection (other agents)

### Claude Code  (~/.claude.json)
\`\`\`json
{ "mcpServers": { "codelens": { "type": "stdio", "command": "node", "args": ["${entryPath}", "${projectPath}"] } } }
\`\`\`

### Cursor  (.cursor/mcp.json)
\`\`\`json
{ "mcpServers": { "codelens": { "command": "node", "args": ["${entryPath}", "${projectPath}"] } } }
\`\`\`

### Cline  (MCP Settings → Add Server → Stdio)
Command: \`node\`  
Args: \`${entryPath} ${projectPath}\`
`;
  }

  // ── Gitignore ────────────────────────────────────────────────────────────────

  private ensureGitignore(workspaceRoot: string): void {
    const gitignorePath = path.join(workspaceRoot, '.gitignore');
    const entry = '\n# CodeLens Graph local index\n.codelens/\n';
    try {
      const existing = fs.existsSync(gitignorePath)
        ? fs.readFileSync(gitignorePath, 'utf-8') : '';
      if (!existing.includes('.codelens/')) {
        fs.appendFileSync(gitignorePath, entry, 'utf-8');
      }
    } catch { /* ignore */ }
  }

  private removeManagedSection(content: string): string {
    const s = content.indexOf('<!-- CODELENS_MANAGED_START -->');
    const e = content.indexOf('<!-- CODELENS_MANAGED_END -->');
    if (s === -1 || e === -1) { return content; }
    return (content.slice(0, s).trimEnd() + '\n' +
            content.slice(e + '<!-- CODELENS_MANAGED_END -->'.length).trimStart()).trim();
  }
}
