import * as fs   from 'fs';
import * as path from 'path';

export const CONFIG_WHITELIST = new Set([
  'package.json', 'tsconfig.json', 'jsconfig.json',
  'vite.config.ts', 'tailwind.config.js',
  'dockerfile', 'readme.md', 'pyproject.toml', 'go.mod',
  'jest.config.js', 'jest.config.ts',
  'vitest.config.ts', 'vitest.config.js',
  'playwright.config.ts',
  '.env.example',
  'nest-cli.json',
  'angular.json',
  'next.config.js', 'next.config.ts',
  'nuxt.config.ts',
  'requirements.txt', 'setup.py', 'poetry.lock',
  'cargo.toml', 'cargo.lock', 'go.sum',
  'package-lock.json'
]);

export function isNodeModulePath(filePath: string): boolean {
  const normalized = filePath.replace(/\\/g, '/');
  return normalized.includes('/node_modules/') || normalized.split('/').includes('node_modules');
}

export function isConfigPath(filePath: string): boolean {
  const name = path.basename(filePath).toLowerCase();
  
  // Treat workspace markdown files (except those generated by CodeLens) as config/info files
  if (name.endsWith('.md') || name.endsWith('.markdown')) {
    const norm = filePath.replace(/\\/g, '/').toLowerCase();
    const isGenerated = norm.includes('.codelens/') || 
                        norm === '.vscode/codelens.instructions.md' || norm.endsWith('/.vscode/codelens.instructions.md') ||
                        norm === '.agents/agents.md' || norm.endsWith('/.agents/agents.md') ||
                        norm === 'claude.md' || norm.endsWith('/claude.md');
    if (isGenerated) { return false; }
    return true;
  }

  // Whitelist check
  if (CONFIG_WHITELIST.has(name)) { return true; }
  
  // Pattern check for *.config.{ts,js,mjs,json}
  if (/\.config\.(ts|js|mjs|json)$/i.test(name)) { return true; }

  return false;
}

export function shouldIndexNodeModuleFile(filePath: string, indexDependencySymbols?: boolean): boolean {
  const name = path.basename(filePath).toLowerCase();
  const normalized = filePath.replace(/\\/g, '/');
  const parts = normalized.split('/node_modules/');
  const afterNodeModules = parts[1] || '';
  if (!afterNodeModules) return false;

  // Always: package.json, readme.md
  if (name === 'package.json' || name === 'readme.md') return true;

  // .d.ts: only index.d.ts or types field entry points if indexDependencySymbols is enabled
  if (name.endsWith('.d.ts') && indexDependencySymbols === true) {
    const segs = afterNodeModules.split('/');
    const isScoped = segs[0]?.startsWith('@');
    const maxParts = isScoped ? 3 : 2; // e.g. @types/react/index.d.ts (3) vs lodash/index.d.ts (2)
    if (segs.length <= maxParts) {
      return true;
    }
  }

  return false;
}

export function matchPathFilter(filePath: string, filter: string, workspaceRoot?: string): boolean {
  const normPath = filePath.replace(/\\/g, '/');
  const name = normPath.split('/').pop() || '';
  
  let relPath = normPath;
  if (workspaceRoot) {
    const normRoot = workspaceRoot.replace(/\\/g, '/').replace(/\/$/, '');
    if (normPath.startsWith(normRoot)) {
      relPath = normPath.slice(normRoot.length).replace(/^\//, '');
    }
  }

  const p = filter.replace(/\\/g, '/').replace(/^\/|\/$/g, '').replace(/(\*\*\/)+/g, '**/');

  if (/^\.[a-zA-Z0-9]+$/.test(p)) {
    return relPath.endsWith(p) || normPath.endsWith(p);
  }

  const literalMatch = () => {
    const seg = p.replace(/\*/g, '').replace(/\//g, '').replace(/{|}|,/g, '');
    return !!seg && (relPath.includes(seg) || name === seg);
  };

  // Filters can come from MCP agents; each wildcard adds a level of polynomial
  // backtracking, so unusually long or wildcard-heavy filters match literally.
  if (p.length > MAX_REGEX_PATTERN_CHARS || (p.match(/\*+/g)?.length ?? 0) > 4) {
    return literalMatch();
  }

  let regexStr = p.replace(/[.+^$()|[\]\\]/g, '\\$&');

  regexStr = regexStr.replace(/{([^}]+)}/g, (_, group) => {
    return '(' + group.split(',').map((s: string) => s.trim()).join('|') + ')';
  });

  regexStr = regexStr
    .replace(/\*\*\//g, '(?:.+/)?')
    .replace(/\/\*\*/g, '(?:/.+)?')
    .replace(/\*/g, '[^/]*')
    .replace(/\?/g, '[^/]');

  if (!p.startsWith('**')) {
    regexStr = '(?:^|/)' + regexStr;
  }

  try {
    const regex = new RegExp('^' + regexStr + '$', 'i');
    if (regex.test(relPath)) { return true; }
    
    const relaxedRegex = new RegExp(regexStr + '$', 'i');
    if (relaxedRegex.test(relPath) || relaxedRegex.test(normPath)) { return true; }
    
    const nameRegex = new RegExp('^' + regexStr + '$', 'i');
    if (nameRegex.test(name)) { return true; }
  } catch {
    return literalMatch();
  }

  return false;
}

// True when filePath resolves to a location inside rootPath. Symlinks are
// resolved first, so a link inside the workspace cannot point reads elsewhere.
export function isPathInside(filePath: string, rootPath: string): boolean {
  const real = (p: string) => {
    try { return fs.realpathSync.native(p); } catch { return path.resolve(p); }
  };
  const rel = path.relative(real(rootPath), real(filePath));
  return rel !== '' && rel !== '..' && !rel.startsWith('..' + path.sep) && !path.isAbsolute(rel);
}

// ─── Agent-supplied regex search ──────────────────────────────────────────────
// Search patterns from MCP agents run on the server's only thread, so a pattern
// with catastrophic backtracking would hang every tool call. Risky patterns are
// rejected (callers fall back to literal search) and tested input is capped.

export const MAX_REGEX_PATTERN_CHARS = 200;
export const MAX_REGEX_INPUT_CHARS   = 1000;

export function compileSearchRegex(query: string): { regex: RegExp | null; rejected: boolean } {
  if (!/[|*?+{}()[\]^$\\&]/.test(query)) { return { regex: null, rejected: false }; }
  if (query.length > MAX_REGEX_PATTERN_CHARS || !isRegexBacktrackSafe(query)) {
    return { regex: null, rejected: true };
  }
  try {
    return { regex: new RegExp(query, 'i'), rejected: false };
  } catch {
    return { regex: null, rejected: false }; // invalid regex → literal search
  }
}

export function regexTestCapped(regex: RegExp, text: string): boolean {
  return regex.test(text.length > MAX_REGEX_INPUT_CHARS ? text.slice(0, MAX_REGEX_INPUT_CHARS) : text);
}

// Rejects backreferences, repeated groups that themselves contain repetition or
// alternation (e.g. (a+)+, (a|aa)*), and more than two unbounded quantifiers.
function isRegexBacktrackSafe(pattern: string): boolean {
  const groupHasRepetition: boolean[] = [];
  let prevAtomWasRiskyGroup = false;
  let unboundedCount = 0;

  const markEnclosingGroup = () => {
    if (groupHasRepetition.length) { groupHasRepetition[groupHasRepetition.length - 1] = true; }
  };

  for (let i = 0; i < pattern.length; i++) {
    const c = pattern[i];

    if (c === '\\') {
      if (/[1-9k]/.test(pattern[i + 1] ?? '')) { return false; }
      i++;
      prevAtomWasRiskyGroup = false;
      continue;
    }
    if (c === '[') {
      i++;
      if (pattern[i] === '^') { i++; }
      if (pattern[i] === ']') { i++; }
      while (i < pattern.length && pattern[i] !== ']') {
        if (pattern[i] === '\\') { i++; }
        i++;
      }
      prevAtomWasRiskyGroup = false;
      continue;
    }
    if (c === '(') {
      groupHasRepetition.push(false);
      prevAtomWasRiskyGroup = false;
      continue;
    }
    if (c === ')') {
      prevAtomWasRiskyGroup = groupHasRepetition.pop() ?? false;
      if (prevAtomWasRiskyGroup) { markEnclosingGroup(); }
      continue;
    }
    if (c === '|') {
      markEnclosingGroup();
      prevAtomWasRiskyGroup = false;
      continue;
    }

    const brace = c === '{' ? /^\{(\d+)(,(\d*))?\}/.exec(pattern.slice(i)) : null;
    if (c === '*' || c === '+' || c === '?' || brace) {
      const unbounded = c === '*' || c === '+' || (brace !== null && brace[2] !== undefined);
      if (unbounded) {
        if (prevAtomWasRiskyGroup) { return false; }
        if (++unboundedCount > 2) { return false; }
      }
      markEnclosingGroup();
      if (brace) { i += brace[0].length - 1; }
      if (pattern[i + 1] === '?') { i++; } // lazy modifier
      prevAtomWasRiskyGroup = false;
      continue;
    }

    prevAtomWasRiskyGroup = false;
  }
  return true;
}

