import * as path from 'path';

export const CONFIG_WHITELIST = new Set([
  'package.json', 'tsconfig.json', 'jsconfig.json',
  'vite.config.ts', 'tailwind.config.js',
  'dockerfile', 'readme.md', 'pyproject.toml', 'go.mod',
  'jest.config.js', 'jest.config.ts',
  'vitest.config.ts', 'vitest.config.js',
  'playwright.config.ts',
  '.env.example',
  'nest-cli.json',
  'angular.json',
  'next.config.js', 'next.config.ts',
  'nuxt.config.ts',
  'requirements.txt', 'setup.py', 'poetry.lock',
  'cargo.toml', 'cargo.lock', 'go.sum',
  'package-lock.json'
]);

export function isNodeModulePath(filePath: string): boolean {
  const normalized = filePath.replace(/\\/g, '/');
  return normalized.includes('/node_modules/') || normalized.split('/').includes('node_modules');
}

export function isConfigPath(filePath: string): boolean {
  const name = path.basename(filePath).toLowerCase();
  
  // Treat workspace markdown files (except those generated by CodeLens) as config/info files
  if (name.endsWith('.md') || name.endsWith('.markdown')) {
    const norm = filePath.replace(/\\/g, '/').toLowerCase();
    const isGenerated = norm.includes('.codelens/') || 
                        norm === '.vscode/codelens.instructions.md' || norm.endsWith('/.vscode/codelens.instructions.md') ||
                        norm === '.agents/agents.md' || norm.endsWith('/.agents/agents.md') ||
                        norm === 'claude.md' || norm.endsWith('/claude.md');
    if (isGenerated) { return false; }
    return true;
  }

  // Whitelist check
  if (CONFIG_WHITELIST.has(name)) { return true; }
  
  // Pattern check for *.config.{ts,js,mjs,json}
  if (/\.config\.(ts|js|mjs|json)$/i.test(name)) { return true; }

  return false;
}

export function shouldIndexNodeModuleFile(filePath: string): boolean {
  const name = path.basename(filePath).toLowerCase();
  const normalized = filePath.replace(/\\/g, '/');
  const parts = normalized.split('/node_modules/');
  const afterNodeModules = parts[1] || '';
  if (!afterNodeModules) return false;

  // Always: package.json, readme.md
  if (name === 'package.json' || name === 'readme.md') return true;

  // .d.ts: only index.d.ts or types field entry points
  if (name.endsWith('.d.ts')) {
    const segs = afterNodeModules.split('/');
    const isScoped = segs[0]?.startsWith('@');
    const maxParts = isScoped ? 3 : 2; // e.g. @types/react/index.d.ts (3) vs lodash/index.d.ts (2)
    if (segs.length <= maxParts) {
      return true;
    }
  }

  return false;
}

export function matchPathFilter(filePath: string, filter: string, workspaceRoot?: string): boolean {
  const normPath = filePath.replace(/\\/g, '/');
  const name = normPath.split('/').pop() || '';
  
  let relPath = normPath;
  if (workspaceRoot) {
    const normRoot = workspaceRoot.replace(/\\/g, '/').replace(/\/$/, '');
    if (normPath.startsWith(normRoot)) {
      relPath = normPath.slice(normRoot.length).replace(/^\//, '');
    }
  }

  const p = filter.replace(/\\/g, '/').replace(/^\/|\/$/g, '');

  if (/^\.[a-zA-Z0-9]+$/.test(p)) {
    return relPath.endsWith(p) || normPath.endsWith(p);
  }

  let regexStr = p.replace(/[.+^$()|[\]\\]/g, '\\$&');

  regexStr = regexStr.replace(/{([^}]+)}/g, (_, group) => {
    return '(' + group.split(',').map((s: string) => s.trim()).join('|') + ')';
  });

  regexStr = regexStr
    .replace(/\*\*\//g, '(?:.+/)?')
    .replace(/\/\*\*/g, '(?:/.+)?')
    .replace(/\*/g, '[^/]*')
    .replace(/\?/g, '[^/]');

  if (!p.startsWith('**')) {
    regexStr = '(?:^|/)' + regexStr;
  }

  try {
    const regex = new RegExp('^' + regexStr + '$', 'i');
    if (regex.test(relPath)) { return true; }
    
    const relaxedRegex = new RegExp(regexStr + '$', 'i');
    if (relaxedRegex.test(relPath) || relaxedRegex.test(normPath)) { return true; }
    
    const nameRegex = new RegExp('^' + regexStr + '$', 'i');
    if (nameRegex.test(name)) { return true; }
  } catch {
    const seg = p.replace(/\*/g, '').replace(/\//g, '').replace(/{|}|,/g, '');
    if (seg && (relPath.includes(seg) || name === seg)) { return true; }
  }

  return false;
}

